/* empty css                      */import{S as l,A as c}from"./assets/vendor-16iyBIrI.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();new l(".my-swiper",{modules:[c],loop:!0,speed:6e3,allowTouchMove:!1,grabCursor:!1,slidesPerView:1.1,spaceBetween:16,autoplay:{delay:0,disableOnInteraction:!1,pauseOnMouseEnter:!1},breakpoints:{1440:{slidesPerView:3,spaceBetween:32}}});document.querySelectorAll(".faq-acc-el-trigger").forEach(n=>{n.addEventListener("click",()=>{const s=n.closest(".faq-acc-el"),o=s.querySelector(".faq-acc-el-descr-frame"),r=n.querySelector("svg"),e=s.classList.contains("open"),t=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M14 4V24" stroke="white" stroke-width="2" stroke-linecap="round" />
  <path d="M24.0049 13.9951L4.00488 13.9951" stroke="white" stroke-width="2" stroke-linecap="round" />
</svg>`,i=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M24.0049 13.9951L4.00488 13.9951" stroke="white" stroke-width="2" stroke-linecap="round" />
</svg>`;e?(s.classList.remove("open"),o.style.maxHeight="0",r.outerHTML=t):(s.classList.add("open"),o.style.maxHeight=o.scrollHeight+"px",r.outerHTML=i)})});
//# sourceMappingURL=index.js.map
